// Copyright (c) 2015 SQUIGGLEE LLC All Rights Reserved.
package com.squigglee.web;

public enum WebAction {
	OP_ADD, OP_DELETE, OP_RESTART, OP_REFRESH,
	CF_SET, CF_ADD, CF_REMOVE, CF_ADD_INDEX, CF_DROP_INDEX, CF_ADD_SKETCH, CF_DROP_SKETCH,
	SK_UPDATE_STATS, SK_POINT_QUERY, SK_RANGE_QUERY, SK_INVERSE_QUERY, SK_UPDATE_HISTOGRAM, SK_UPDATE_SAMPLING_HISTOGRAM, SK_CONFIGURE,
	DR_CONFIGURE, DR_CAPTURE, DR_MATCH, DR_UPDATE_TS, DR_FETCH_PATTERN, DR_FETCH_AHEAD,
	ST_UPDATE
}
