package com.squigglee.core.entity;

import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;

public class Stream {
	private String id = null;
	private String guid = null;
	private String cluster = null;
	private int ln;
	private String name;
	private boolean isDerived;	// whether this stream is a original/raw time series data stream or calculated via CEP 
	private boolean isPersisted; // whether events generated by queries are  (briefly) for clients to pick up 
	private boolean isStored; // whether events generated by queries are stored back as another original/raw time series data 
	
	//examples 
	//1) false,false,false --> for original raw time series data, stored by default  
	//2) true, false, false --> CEP engine events, in-memory only, intermediate calculations for complex queries & joins   
	//3) true, true, false --> CEP engine events, stored briefly for subscribing clients to pick up e.g. alerts 
	//4) true, false, true --> new time series generated by CEP engine, stored as a new time series e.g. rollups, window calculations etc. 
	// example 4 itself is used internally, by default, to roll up raw time series automatically
	// thus, millisecond data --> auto rolled up to seconds, minutes, hours, days, and years, thus enabling retrieval at any frequency 
	
	public Stream() {}
	
	public Stream(String guid, String cluster, int ln, String name, boolean isDerived, boolean isPersisted, boolean isStored) {
		this("S" + guid.replaceAll("-", "").toUpperCase(), guid, cluster, ln, name, isDerived, isPersisted, isStored);
	}
	
	public Stream(String id, String guid, String cluster, int ln, String name, boolean isDerived, boolean isPersisted, boolean isStored) {
		this.id = id;
		this.guid = guid;
		this.cluster = cluster;
		this.ln = ln;
		this.name = name;
		this.isDerived = isDerived;
		this.isPersisted = isPersisted;
		this.isStored = isStored;
	}
	
	public Stream(String guid, String cluster, int ln, String name) {
		this(guid, cluster, ln, name, false, false, false);	// default for raw stored time series data
	}
	
	public int getLn() {
		return ln;
	}
	public void setLn(int ln) {
		this.ln = ln;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public boolean isDerived() {
		return isDerived;
	}
	public void setDerived(boolean isDerived) {
		this.isDerived = isDerived;
	}
	public String getCluster() {
		return cluster;
	}
	public void setCluster(String cluster) {
		this.cluster = cluster;
	}
	public String getGuid() {
		return guid;
	}

	public void setGuid(String guid) {
		this.guid = guid;
	}
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	public boolean isPersisted() {
		return isPersisted;
	}
	public void setPersisted(boolean isPersisted) {
		this.isPersisted = isPersisted;
	}
	
	@Override
	public String toString() {
		return "[guid=" + guid + ",cluster=" + cluster + ",ln=" + ln + ",id=" + id  + ",name=" + name + ",isDerived=" + isDerived 
				+ ",isPersisted=" + isPersisted + "]";
	}

	@Override
	public int hashCode() {
		return new HashCodeBuilder(13,97).append(guid).append(cluster).append(ln).append(id).append(name)
				.append(isDerived).append(isPersisted).toHashCode();
	}
	
	@Override
	public boolean equals(Object obj) {
		if (!(obj instanceof Stream))
			return false;
		if (obj == this)
			return true;
		Stream rhs = (Stream) obj;
		return new EqualsBuilder().append(this.guid, rhs.getGuid()).append(this.cluster, rhs.getCluster()).append(this.ln, rhs.getLn())
				.append(this.id, rhs.getId()).append(this.name, rhs.getName()).append(isDerived, rhs.isDerived())
				.append(isPersisted, rhs.isPersisted()).isEquals();
	}

	public boolean isStored() {
		return isStored;
	}

	public void setStored(boolean isStored) {
		this.isStored = isStored;
	}
}
