// Copyright (c) 2015 SQUIGGLEE LLC All Rights Reserved.
package com.squigglee.core.entity;

public enum View {
	MASTERDATA, BULKDATA,
	//core time series data views
	INTEGERS, LONGS, BOOLEANS, DOUBLES, FLOATS, STRINGS, 
	CLOBS, BLOBS, BIGINTEGERS, BIGDECIMALS, 
	//sampled time series data views
	SAMPLEDINTEGERS, SAMPLEDLONGS, SAMPLEDBOOLEANS, SAMPLEDDOUBLES, SAMPLEDFLOATS, SAMPLEDSTRINGS, 
	SAMPLEDCLOBS, SAMPLEDBLOBS, SAMPLEDBIGINTEGERS, SAMPLEDBIGDECIMALS,
	//time series queries on sketches of time series data 
	SKETCHEDINTEGERS, SKETCHEDLONGS, SKETCHEDBOOLEANS, SKETCHEDDOUBLES, SKETCHEDFLOATS, SKETCHEDSTRINGS, 
	SKETCHEDCLOBS, SKETCHEDBLOBS, SKETCHEDBIGINTEGERS, SKETCHEDBIGDECIMALS,
	//pattern repository for multi-dimensional time series queries  
	PATTERNINTEGERS, PATTERNLONGS, PATTERNBOOLEANS, PATTERNDOUBLES, PATTERNFLOATS, PATTERNSTRINGS,
	PATTERNCLOBS, PATTERNBLOBS, PATTERNBIGINTEGERS, PATTERNBIGDECIMALS,
	//INTEGERPATTERNS, LONGPATTERNS, BOOLEANPATTERNS, DOUBLEPATTERNS, FLOATPATTERNS, STRINGPATTERNS, 
	//CLOBPATTERNS, BLOBPATTERNS, BIGINTEGERPATTERNS, BIGDECIMALPATTERNS,
	// multi-dimensional index retrievals 
	MATCHEDINTEGERS, MATCHEDLONGS, MATCHEDBOOLEANS, MATCHEDDOUBLES, MATCHEDFLOATS, MATCHEDSTRINGS, 
	MATCHEDCLOBS, MATCHEDBLOBS, MATCHEDBIGINTEGERS, MATCHEDBIGDECIMALS
}
