package com.squigglee.cloud.ec2;

public enum ScriptType {
	CREATE_TOPOLOGY, CONF_VOLS, CONF_PREREQ, CONF_CASS, CONF_JBOSS, CONF_TSR, CONFIGURE, CONFIGURE_NODE, START_ALL, 
	START_NODE, SET_SCHEMA, START_SERVICES_COORD, START_SERVICES_ALL, START_SERVICES_NODE, STOP_SERVICES_NODE, DELETE_TOPOLOGY
}
